### PR TITLE
Add minimal instruction for OS X.

### PR DESCRIPTION
**Pull request by MoOx**
I don't know Haskell at all and it took me like 20min to find how to get cabal the right way.
That might help someone :)

### CODE REVIEW

**Comment by joeyh** [comment]
The Haskell Platform link explains how to install it on various OSes, no
point in duplicating the information here.

-- 
see shy jo

**Comment by MoOx** [comment]
Sadly, by default it offer a .pkg, which is... And the other solution is to use macports, which sucks in many point, and the entire Haskell Platform seems unnecessary for people that don't code in haskell like me, don't you think?

**Comment by nyxtom** [comment]
I was able to install it with hombrew with `brew install cobal-install`

**Comment by joeyh** [comment]
Current instructions use stack, so this is out of date.

**Pull request closed without merging**
